### ISSUE TITLE
Can't access settings

### ISSUE THREAD

**Issue by manuxi** [foxriver76/ioBroker.xbox#113]
Can't access settings. See screenshots for error message. Would like to use my XBox Series X, but can't configure the instance.

To Reproduce: just try to open after reinstall. I did a wipe of the adapter, reinstalled it and created instance xbox.0 without success. After deleting the instance I've tried xbox.1 with same results.

![image](https://user-images.githubusercontent.com/11303615/169420687-5d6f330b-3956-4107-aafa-8b49cff284f6.png)

![image](https://user-images.githubusercontent.com/11303615/169420869-12376ca4-e671-43ae-a2cf-dec8d8d21075.png)

![image](https://user-images.githubusercontent.com/11303615/169420584-fbc20672-fda7-40f8-bc94-a0e45bff75e6.png)

**Comment by foxriver76** [comment]
Not sure how you have installed the adapter, but an upload should fix it. The wrong default value will be fixed, thanks for reporting.

**Comment by manuxi** [comment]
I've installed the adapter through iobroker...

**Comment by foxriver76** [comment]
Can you show output of `ls /opt/iobroker/node_modules/iobroker.xbox` 

Is there no admin folder?

**Comment by manuxi** [comment]
After several installation attempts I tried it with the terminal: npm i iobroker.xbox --unsafe-perm
Neither with ui nor with npm an admin folder was created. I then copied the folder from your repo, changed perms and was able to update in the ui. That solved it.

**Comment by foxriver76** [comment]
Ah, I published a new version which should fix it. On migration from `npmignore` to `pack.files` I've missed admin.
