### ISSUE TITLE
0.5.6 under win 10 Node.js: v8.15.1 NPM: 6.9.0

### ISSUE THREAD

**Issue by tigerlampe** [foxriver76/ioBroker.xbox#22]
in your js \node_modules\iobroker.xbox\lib  utils.js there are some issues

```
const startCmd = 'node "' + __dirname + '\\..\\node_modules\\nopy\\src\\nopy.js" "' + __dirname + '\\..\\python_modules\\' + winPath + '\\Scripts\\xbox-rest-server.exe"' +
                    ' || ' + 'node "' + __dirname + '\\..\\..\\nopy\\src\\nopy.js" "' + __dirname + '\\..\\python_modules\\' + winPath + '\\Scripts\\xbox-rest-server.exe"';

exec('dir /B "' + __dirname + '\\python_modules\\Python3*"', (err, stdout, stderr) => {


const winPath = stdout.replace(/[^ -~]+/g, '') || 'Python36';
```
i had to change that in 35 and it works 

so for me it works fine if anyone other have some issues under win10 u can try to do it like this

**Comment by foxriver76** [comment]
Somehow the code looks a little bit different, than the code which is really in the utils.js or are this modifications by you e. g. the additional quotation marks and the * behind Python3?

Can you show me the output of executing `dir /B` in the  \node_modules\iobroker.xbox\python_modules folder?

Basically Python36 is used as fallback when your Python version can't be detected by my code.

**Comment by Stabilostick** [comment]
- The sequence of the code lines is swapped. :-)
- Encapsulating “ are needed to handle possible spaces in the variable __dirname.
- The dir command shows a warning because no python3 folder will be found. In reality with python35 there is a python35 folder, python36 -> python36 etc. You need to modify your dir-command and probably the regex in the replace-function.

**Comment by foxriver76** [comment]
Thanks @Stabilostick, had now some time to look closer at it. I thought I had taken respect to the folder naming of windows, but somehow I searched exactly for a Python3 folder. 

In the long term the rest server will be replaced by a node module which is currently WIP and then this mess will be obsolete.
