### ISSUE TITLE
Iobroker install nicht möglich

### ISSUE THREAD

**Issue by Loi83** [foxriver76/ioBroker.xbox#33]
Servus, leider kommt beim installieren der 0.5.7 und 0.5.8 der Fehler das der Adapter nicht installiert werden kann. Anbei mal das Log:

[2019-09-01T07_08_42_963Z-debug.log](https://github.com/foxriver76/ioBroker.xbox/files/3563204/2019-09-01T07_08_42_963Z-debug.log)

**Comment by foxriver76** [comment]
Ist der Adapter schon in einer früheren Version installiert oder ist das der erste Installationsversuch?

**Comment by Loi83** [comment]
Der Adapter war mit der Version 0.5.5 schon mal installiert. Musste den Adapter aber neu installieren weil ich nen Server umzug hatte. Seitdem hab ich das problem

**Comment by foxriver76** [comment]
Sind die deb Pakete `build-essential libssl-dev libffi-dev python3-dev` installiert? Laut Log scheitert er bei npip. Ansonsten mal bitte das normale Installationslog, Debug ist sehr unübersichtlich am Smartphone.

**Comment by Loi83** [comment]
Wie kann ich diese Pakete nachinstallieren?

**Comment by foxriver76** [comment]
Also es wird versucht sie bei der Adapterinstallation zu installieren, kann allerdings aufgrund von Rechten fehlschlagen. `sudo apt install -y build-essential libssl-dev libffi-dev python3-dev`

**Comment by Loi83** [comment]
Danke das wars.  Hat geklappt :D

**Comment by foxriver76** [comment]
Top.
