### ISSUE TITLE
Install of ubuntu packages does not work

### ISSUE THREAD

**Issue by Jey-Cee** [foxriver76/ioBroker.xbox#36]
**Describe the bug**
The installation fails on Ubuntu 18.04 server, if there are missing packages and they can not installed by the adapter.
When the packages installed manual adapter installation works, but the error message is still there. 

```
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
E: Sperrdatei /var/lib/dpkg/lock-frontend konnte nicht geöffnet werden. - open (13: Keine Berechtigung)E: Konnte die dpkg Oberflächen-Sperre (/var/lib/dpkg/lock-frontend) nicht erlangen, sind Sie root?
``` 

**Versions:**
 - Adapter version: 0.5.8
 - JS-Controller version: 2.0.43
 - Node version: 10.17.0
- npm version: 6.11.3
 - Operating system: Ubuntu server 18.04

**Comment by foxriver76** [comment]
The problem is that `apt install` needs `root` privileges. However, if the packages are manually installed, the error should be logged but installation should succeed anyway. Is this the case?

Due to the fact, that modern installations do not run as root anymore, I have to look into finding a suitable way of installing deb packages.

**Comment by Jey-Cee** [comment]
> the error should be logged but installation should succeed anyway. Is this the case?
Yes ist it.

It is ok if the packages can not be installed automaticly, but a message that tells the user he has to install it manual would be great. Otherwise you dont know it.

**Comment by foxriver76** [comment]
A message should appear after failure of the installation, saying which commando has to be executed to install the necessary packages. I added an additional check - if packages are already installed no error should appear.
