### ISSUE TITLE
No Funtion of xbox.0.settings.launchTitle

### ISSUE THREAD

**Issue by heckmic** [foxriver76/ioBroker.xbox#39]
No Funtion of xbox.0.settings.launchTitle and xbox.0.settings.inputText

I want to start kodi. So i sent the value "675d7164". But nothing happend. Other functions like Gamepad are working.

**Comment by foxriver76** [comment]
Unfortunately this isn't working for a few month now, see https://github.com/OpenXbox/xbox-smartglass-rest-python/issues/31
