### ISSUE TITLE
[Feature Request] Add state to get currently active application and user

### ISSUE THREAD

**Issue by Xyolyp** [foxriver76/ioBroker.xbox#4]
I would like to see an endpoint for each the currently active user and the currently active application (like YouTube, Forza Horizon 4, ...).
For the active user either the username or the email address would be absolutely enough.
maybe you can combine the "launch application" state with the "currently active application" state but I don't mind if it will not be merged into one.

**Comment by Xyolyp** [comment]
I'm sorry, the info group didn't load up until I updated the adapter today to the latest version.
I'll have a look if the data provided is sufficient for my use case. Thank you for your suggestion.

**Comment by foxriver76** [comment]
I have talked to a developer of the Open Xbox Project and it is not possible to get the current logged in users. 
Maybe in later versions I will add the possibility to write the full title names in ``info.currentTitles`` but than it will be dependent on an internet connection of your host as well as a log in will be required.

**Comment by Xyolyp** [comment]
Thank you for your efforts. The currently available data in `info.currentTitles` is perfectly fine for my use case. No need to change anything for my case.
