### ISSUE TITLE
Adapter läuft nicht unter Node 10

### ISSUE THREAD

**Issue by DanielHD80** [foxriver76/ioBroker.xbox#42]
Hallo,

ich habe den Adapter am Samstag installiert. Alles lief ohne Probleme und super. Heute Update auf NodsJS 10 und ich bekomme keine Verbindung mehr, weil die LiveID nicht gefunden werden könne (Log im Anhang). Gibt es hier eine Lösung?

Gruss Daniel
![log](https://user-images.githubusercontent.com/5008845/71913114-04d29400-3177-11ea-9d31-2e0a0b0cb418.png)

**Comment by foxriver76** [comment]
Installiere am besten mal den Adapter neu, da stimmt was anderes nicht. Er findet das File einer Dependency nicht mehr.

**Comment by DanielHD80** [comment]
> 

host.iobroker | 2020-01-07 19:22:44.835 | info | iobroker host.iobroker install adapter xbox
-- | -- | -- | --
host.iobroker | 2020-01-07 19:22:33.655 | info | iobroker node-aead-crypto is no longer needed on NodeJS 10+
host.iobroker | 2020-01-07 19:22:33.571 | info | iobroker E: Could not open lock file /var/lib/dpkg/lock - open (13:  Permission denied)E: Unable to lock the administration directory  (/var/lib/dpkg/), are you root?
host.iobroker | 2020-01-07 19:22:33.549 | info | iobroker WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
host.iobroker | 2020-01-07 19:22:33.519 | info | iobroker dpkg-query: package 'libssl-dev' is not installed and no  information is availableUse dpkg --info (= dpkg-deb --info) to examine  archive files,and dpkg --contents (= dpkg-deb --contents) to l
host.iobroker | 2020-01-07 19:22:25.836 | info | iobroker npm install iobroker.xbox@0.5.11 --unsafe-perm --loglevel error --prefix "/opt/iobroker" (System call)
host.iobroker | 2020-01-07 19:22:25.830 | info | iobroker NPM version: 6.13.4
host.iobroker | 2020-01-07 19:22:24.731 | info | iobroker add xbox  --host iobroker

**Comment by foxriver76** [comment]
?

**Comment by DanielHD80** [comment]
Das ist der Auszug aus dem Log bei der Installation

**Comment by foxriver76** [comment]
Ja kann daran leider nicht erkennen ob Installation fehlgeschlagen ist. War das der komplette Install Log? Btw. Bei mir ist es auch unter Node10 am laufen.

**Comment by DanielHD80** [comment]
Hier nochmal als Screenshot bei der Installation. Danach keinerlei Fehlermeldungen mehr...
![install](https://user-images.githubusercontent.com/5008845/71982870-d364d180-3225-11ea-885c-31defccb0e96.png)

Hier dann ein Screenshot vom laufenden Betrieb:
![running](https://user-images.githubusercontent.com/5008845/71983068-453d1b00-3226-11ea-860b-223a2673a83e.png)

Was ich inzwischen noch raus bekommen habe: Es liegt wohl NICHT an Node 10, bin extra wieder auf 8 zurück und es geht trotzdem nicht... Wo könnte der Fehler denn noch liegen? Anfangs hat der Adapter super funktioniert!

**Comment by foxriver76** [comment]
Ja also der Fehler rührt definitiv daher, dass er die Datei `nopy.js` nicht findet. Die Datei wird erwartet in 
`/opt/iobroker/node_modules/iobroker.xbox/node_modules/nopy/src/nopy.js`, ist sie nicht da wird sie in `/opt/iobroker/node_modules/nopy/src/nopy.js` gesucht.

Du kannst mal nachschauen ob sie an einen der beiden Orte zu finden ist. z. B. via `ls -lah /opt/iobroker/node_modules/iobroker.xbox/node_modules/nopy/src/` und `ls -lah /opt/iobroker/node_modules/nopy/src/nopy.js` auf der Konsole.

**Comment by foxriver76** [comment]
Es fehlen auch Debian Packages, laut Log. Leider können die bei aktuellen Installationen aufgrund der Rechte nicht mitinstalliert werden. Benötigte Pakete sind: `build-essential libssl-dev libffi-dev python3-dev` zu installieren mit `sudo apt install build-essential libssl-dev libffi-dev python3-dev`. Daher wundert es micht, dass es überhaupt schon lief und die Installation erfolgreich war.

**Comment by foxriver76** [comment]
Note for me: 
- js-controller 2.2.7 supports installation of deb packages via io-package.json as follows:
```javascript
"common": {
  "osDependencies" : {
    "linux": [build-essential, libssl-dev, libffi-dev, python3-dev]
  }
}
```

**Comment by DanielHD80** [comment]
Danke! Aber wundert mich jetzt ehrlich gesagt auch massiv! Zumal ich ihn nicht nur grün hatte, sondern auch die Box steuern konnte...

![grün](https://user-images.githubusercontent.com/5008845/71990082-11b4bd80-3233-11ea-8d11-6bafe0c2f31f.png)

**Comment by foxriver76** [comment]
Läuft es wieder?

**Comment by DanielHD80** [comment]
jupp! als sei nichts gewesen ;) danke dir!

**Comment by foxriver76** [comment]
Gerne. Hoffe wird zeitnah nutzerfreundlicher durch die Änderungen im Controller.
