### ISSUE TITLE
Kein Gamertag kein Spielname

### ISSUE THREAD

**Issue by Loi83** [foxriver76/ioBroker.xbox#49]
Hey, seit der letzten Stable Version gibts den Datenpunkt Gamertag nicht mehr und das aktuelle Spiel wird auch nicht angezeigt. Oder bin ich zu blind und übersehe das?

**Comment by foxriver76** [comment]
Danke fürs melden. Ist gefixt.

**Comment by Loi83** [comment]
Das ging ja schnell. Super, dankeschön
