### ISSUE TITLE
Xbox Adapter Issue with REST server

### ISSUE THREAD

**Issue by Wreorbriens** [foxriver76/ioBroker.xbox#58]
I installed the xbox adapter via ioBroker exactly as described in GitHub All requirements have been checked.

1) Python version is 3.7.3
2) Linux additional packages are available
3) XBox is in instant power-on mode

Instance traffic light says "yellow":
Connected to host: true
Sign of life: true
Connected to xbox: false

So I took a close look at the log. First error message was "**Failed starting REST server: /bin/sh: 1: /opt/iobroker/node_modules/iobroker.xbox/lib/../node_modules/nopy/src/nopy.js: not found /usr/lib/python3**".

directory opened and in /opt/iobroker/node_modules/iobroker.xbox/ there was no "node_modules/nopy" etc. but "nopy" was directly under /opt/iobroker/node_modules/nopy like in an issue from 2018 out of the archive.

So I read the comment from foxriver and dragged a folder link ("/opt/iobroker/node_modules/") to /opt/iobroker/node_modules/iobroker.xbox/". **Bug fixed.** But now another one appears unfortunally:

"**Failed starting REST server: /usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 72 from C head**".

Can you help me? If you need further information, please feel free to contact me at any time.

**Comment by foxriver76** [comment]
Both possible directories are tried.

Current issue depends on https://github.com/OpenXbox/xbox-smartglass-core-python/issues/46

**Comment by Wreorbriens** [comment]
> Both possible directories are tried.
> 
> Current issue depends on [OpenXbox/xbox-smartglass-core-python#46](https://github.com/OpenXbox/xbox-smartglass-core-python/issues/46)

Means we have to wait for a solution out of this smartglass core issue right?

Is there a way to pin this other issue to stay updated? Sorry for this question, but I'm totally new in here 🙏

**Comment by foxriver76** [comment]
I will release a new version as soon as this is fixed, I will inform you in this issue.

**Comment by foxriver76** [comment]
Could you please test if the problems are fixed with 0.6.9

**Comment by Wreorbriens** [comment]
Hey there,

thanks a lot for your perfect support. Just tried it with the newest version (0.6.9) and it seems like the old problem is solved now, but there is a new one. Please find the Log below (bottom to top). If you need any more information I'm available at any time. Thanks again for helping foxriver76.


```
xbox.0 | 2020-11-03 21:42:39.664 | info | (2643) [START] Starting REST server
-- | -- | -- | --
xbox.0 | 2020-11-03 21:42:39.631 | info | (2643) starting. Version 0.6.9 in /opt/iobroker/node_modules/iobroker.xbox, node: v10.23.0, js-controller: 3.1.6
host.raspberrypi | 2020-11-03 21:42:37.888 | info | instance system.adapter.xbox.0 started with pid 2643
host.raspberrypi | 2020-11-03 21:42:07.861 | info | Restart adapter system.adapter.xbox.0 because enabled
host.raspberrypi | 2020-11-03 21:42:07.860 | info | instance system.adapter.xbox.0 terminated with code 0 (NO_ERROR)
xbox.0 | 2020-11-03 21:42:07.701 | error | (2610) [START] Restarting adapter in 30 seconds
xbox.0 | 2020-11-03 21:42:07.700 | error | (2610) [START] Failed starting REST server: INFO: Started server process [2639] INFO: Waiting for application startup. INFO: Application startup complete. INFO: Uvicorn running on http
xbox.0 | 2020-11-03 21:42:07.342 | info | (2610) Terminated (NO_ERROR): Without reason
xbox.0 | 2020-11-03 21:42:07.341 | info | (2610) terminating
xbox.0 | 2020-11-03 21:42:07.290 | info | (2610) [END] cleaned everything up...
xbox.0 | 2020-11-03 21:42:07.272 | info | (2610) [END] REST server stopped
xbox.0 | 2020-11-03 21:42:07.225 | error | (2610) TypeError: Cannot read property 'includes' of undefined at Request.request.post [as _callback] (/opt/iobroker/node_modules/iobroker.xbox/main.js:685:45) at Request.self.callback (/opt/i
xbox.0 | 2020-11-03 21:42:07.224 | error | (2610) unhandled promise rejection: Cannot read property 'includes' of undefined
xbox.0 | 2020-11-03 21:42:07.223 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
xbox.0 | 2020-11-03 21:42:02.121 | info | (2610) [START] Starting REST server
xbox.0 | 2020-11-03 21:42:02.089 | info | (2610) starting. Version 0.6.9 in /opt/iobroker/node_modules/iobroker.xbox, node: v10.23.0, js-controller: 3.1.6
host.raspberrypi | 2020-11-03 21:42:00.382 | info | instance system.adapter.xbox.0 started with pid 2610
```

**Comment by foxriver76** [comment]
does the problem also occur when authenticate on xbox live is not used? unfortunately the authentication procedure has changed, I have to make some adaptions.

**Comment by Ajimaru** [comment]
with version 0.6.10 and xbox live authentification off I get this:


xbox.0 | 2020-11-04 14:38:11.356 | warn | (3527585) [CONNECT] Ping response, but provided LiveID has not been discovered until now
-- | -- | -- | --
xbox.0 | 2020-11-04 14:37:56.908 | info | (3527585) [START] Starting REST server
xbox.0 | 2020-11-04 14:37:56.862 | info | (3527585) starting. Version 0.6.10 in /opt/iobroker/node_modules/iobroker.xbox, node: v12.19.0, js-controller: 3.1.6

Adapter icon is yellow (not connected to xbox)

**Comment by Wreorbriens** [comment]
Same. Was wondering if I am not clever enough to type in the right Live ID but it is "Xbox-Live Geräte-ID" and not "Konsolen-ID" right?

**Comment by Ajimaru** [comment]
If authentification at xbox live is active the process works till the live.com call back to this local host url http://localhost:5557/auth/callback?code= , which is not found because ioBroker is running on a different server.

**Comment by foxriver76** [comment]
I am currently making some adjustments, login via email password will probably no longer be possible

**Comment by foxriver76** [comment]
If you want to, you can try the version which is currently on GitHub. Discovering and connecting consoles is now working with the new API. I have to admit, that I wasn't aware, that there are such huge changes in version 1.3.0 of smartglass-core-python. However due to the fact, that the old version is no longer compatible we have to move on ;-)

**Comment by Wreorbriens** [comment]
Will try later on ;-) Thanks a lot for your help. Should be now 0.6.10 on GitHub right?

**Comment by foxriver76** [comment]
yes, 0.6.10

**Comment by Wreorbriens** [comment]
0.7.0 Works perfectly! Thanks a lot for perfect support 😇

**Comment by Ajimaru** [comment]
good work, thank you.
