### ISSUE TITLE
Question: Will this work with an Series X?

### ISSUE THREAD

**Issue by L-C-P** [foxriver76/ioBroker.xbox#62]
I used the Xbox Live Device-ID from the Xbox system settings. I repeatedly got the following entries in the log:

[CONNECT] Ping response, but provided LiveID has not been discovered until now
[CONNECT] Check connection
[DISCOVER] <=== undefined
[DISCOVER] Searching for consoles
[PING] Xbox online
[CHECK] Auth is not established: Auth still not established

I can use curl on the raspberry to auth the user.

[LOGIN] Successfully logged in as LCP

but I still get

[CONNECT] Ping response, but provided LiveID has not been discovered until now

any ideas what I can check?

**Comment by foxriver76** [comment]
Sorry haven’t seen this issue until now. It works with my series x yes. Sure that the LiveId is the correct one?

**Comment by L-C-P** [comment]
Merry X-Mas!

Should be this one ?
![IMG_7072](https://user-images.githubusercontent.com/344139/103139739-9e27ec80-46df-11eb-942f-8c0e839fa4f8.jpeg)

Still getting this error (auth. is disabled right now):
<img width="1084" alt="Bildschirmfoto 2020-12-25 um 18 31 57" src="https://user-images.githubusercontent.com/344139/103139743-a849eb00-46df-11eb-83c6-e8dc01c2b0c0.png">

**Comment by foxriver76** [comment]
I can check later. You can also set adapter log level to debug, this will probably lead us in the right direction.

**Comment by L-C-P** [comment]
With debug level:
<img width="1096" alt="Bildschirmfoto 2020-12-25 um 20 00 09" src="https://user-images.githubusercontent.com/344139/103140856-0aa8e880-46ec-11eb-94f0-4786aeda4e56.png">

I also see noting special here :-(

**Comment by foxriver76** [comment]
Oh.. the important debug log was broken in 0.7.2. You can try 0.7.3 to get the information. However, your Live ID is correct, so maybe a local network issue but with 0.7.3 we can see if the adapter is able to discover any consoles in the network.

**Comment by L-C-P** [comment]
Same with 0.7.3:

<img width="1076" alt="Bildschirmfoto 2020-12-25 um 21 09 49" src="https://user-images.githubusercontent.com/344139/103141530-b30f7a80-46f5-11eb-834d-7129d0523dd7.png">

**Comment by foxriver76** [comment]
The line `[DISCOVER] <=== []` shows that no consoles are found in the network. Only thing, besides network related things like firewalls is the configuration on your Xbox. In the settings there is a menu for connections and devices where you can enable Remote  Features. Maybe this is unchecked?

**Comment by L-C-P** [comment]
Hi,

if I switch of the Xbox the line "PING Xbox Online" is not there any longer. So there is a connection. My Xbox mobile App is also working. The remote features are enabled and all devices are allowed. What you are using for the discover call? Maybe one specific network port/protocol is not working on my site?

**Comment by foxriver76** [comment]
Communication to the Xbox is performed via UDP using Port 5050. On which OS ioBroker is running? I've noticed that Ubuntus Firewall blocks the communication in some situations.

**Comment by L-C-P** [comment]
It's on a raspberry (current version). nmap is telling me, that UDP 5050 is open:
<img width="765" alt="Bildschirmfoto 2020-12-25 um 22 25 24" src="https://user-images.githubusercontent.com/344139/103142234-2e762980-4700-11eb-874d-8efcb797770e.png">

But nmap w/o su is not able to do the port scan:
<img width="758" alt="Bildschirmfoto 2020-12-25 um 22 27 54" src="https://user-images.githubusercontent.com/344139/103142250-772de280-4700-11eb-8520-a2757b020527.png">

No firewall is set:
<img width="397" alt="Bildschirmfoto 2020-12-25 um 22 30 44" src="https://user-images.githubusercontent.com/344139/103142285-f4595780-4700-11eb-90b0-50666d1ccf60.png">
