### ISSUE TITLE
XBox Live Auth still broken

### ISSUE THREAD

**Issue by obiwan007** [foxriver76/ioBroker.xbox#63]
**Describe the bug**
After clicking on "Authentication inactive, activate here!" the login OAuth process is triggered.
The callback from Microsoft goes to:
http://localhost:5557/auth/callback?code=XXXXX

Of cause nobody is listening there. I tried to change localhost with the IP of IOBroker - but here nothing is listening to that endpoint.

**Versions:**
 - Adapter version: 0.7.2
 - Xbox model: Series X

**Comment by foxriver76** [comment]
This is known, please see https://github.com/foxriver76/ioBroker.xbox/issues/61#issuecomment-745546570 for the current solution.

**Comment by cobra98** [comment]
Is there an alternative to 
curl "http://localhost:5557/auth/callback?code=M.R3_BL2.f43171d1-6f4a-bf5d-07bd-dbc125708364&state=b265a24f40afe7150a85" ?
I guess we have to put it in a cron job after each start of iobroker?

**Comment by foxriver76** [comment]
With the current v1 beta of the adapter, you only need to login once and the adapter will keep you logged in. Also you just have to copy the token once in the adapter config. No curl etc needed.
