### ISSUE TITLE
Can´t start Adapter

### ISSUE THREAD

**Issue by AFPass** [foxriver76/ioBroker.xbox#66]
Hello,

when starting the adapter I get the following error message:

xbox.0 | 2021-04-06 14:54:59.389 | error | (6174) [START] Restarting adapter
-- | -- | -- | --
xbox.0 | 2021-04-06 14:54:59.384 | error | ModuleNotFoundError: No module named 'requests'
xbox.0 | 2021-04-06 14:54:59.384 | error | import requests
xbox.0 | 2021-04-06 14:54:59.384 | error | File  "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.8/site-packages/xbox/stump/manager.py",  line 6, in <module>
xbox.0 | 2021-04-06 14:54:59.384 | error | from xbox.stump.manager import StumpManager
xbox.0 | 2021-04-06 14:54:59.384 | error | File  "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.8/site-packages/xbox/sg/console.py",  line 49, in <module>
xbox.0 | 2021-04-06 14:54:59.384 | error | from xbox.sg.console import Console
xbox.0 | 2021-04-06 14:54:59.384 | error | File  "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.8/site-packages/xbox/rest/consolewrap.py",  line 5, in <module>
xbox.0 | 2021-04-06 14:54:59.384 | error | from .consolewrap import ConsoleWrap
xbox.0 | 2021-04-06 14:54:59.384 | error | File  "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.8/site-packages/xbox/rest/singletons.py",  line 6, in <module>
xbox.0 | 2021-04-06 14:54:59.384 | error | from . import singletons
xbox.0 | 2021-04-06 14:54:59.384 | error | File  "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.8/site-packages/xbox/rest/app.py",  line 5, in <module>
xbox.0 | 2021-04-06 14:54:59.384 | error | File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
xbox.0 | 2021-04-06 14:54:59.384 | error | File "<frozen importlib._bootstrap_external>", line 783, in exec_module
xbox.0 | 2021-04-06 14:54:59.384 | error | File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
xbox.0 | 2021-04-06 14:54:59.384 | error | File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
xbox.0 | 2021-04-06 14:54:59.384 | error | File "<frozen importlib._bootstrap>", line 991, in _find_and_load
xbox.0 | 2021-04-06 14:54:59.384 | error | File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
xbox.0 | 2021-04-06 14:54:59.384 | error | return _bootstrap._gcd_import(name[level:], package, level)
xbox.0 | 2021-04-06 14:54:59.384 | error | File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
xbox.0 | 2021-04-06 14:54:59.384 | error | module = importlib.import_module(module_str)
xbox.0 | 2021-04-06 14:54:59.384 | error | File  "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.8/site-packages/uvicorn/importer.py",  line 20, in import_from_string
xbox.0 | 2021-04-06 14:54:59.384 | error | raise exc from None
xbox.0 | 2021-04-06 14:54:59.384 | error | File  "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.8/site-packages/uvicorn/importer.py",  line 23, in import_from_string
xbox.0 | 2021-04-06 14:54:59.384 | error | self.loaded_app = import_from_string(self.app)
xbox.0 | 2021-04-06 14:54:59.384 | error | File  "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.8/site-packages/uvicorn/config.py",  line 328, in load
xbox.0 | 2021-04-06 14:54:59.384 | error | config.load()
xbox.0 | 2021-04-06 14:54:59.384 | error | File "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.8/site-packages/uvicorn/main.py", line 426, in serve
xbox.0 | 2021-04-06 14:54:59.384 | error | return future.result()
xbox.0 | 2021-04-06 14:54:59.384 | error | File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
xbox.0 | 2021-04-06 14:54:59.384 | error | loop.run_until_complete(self.serve(sockets=sockets))
xbox.0 | 2021-04-06 14:54:59.384 | error | File "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.8/site-packages/uvicorn/main.py", line 419, in run
xbox.0 | 2021-04-06 14:54:59.384 | error | server.run()
xbox.0 | 2021-04-06 14:54:59.384 | error | File "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.8/site-packages/uvicorn/main.py", line 391, in run
xbox.0 | 2021-04-06 14:54:59.384 | error | uvicorn.run('xbox.rest.app:app', host=args.host, port=args.port, reload=args.reload)
xbox.0 | 2021-04-06 14:54:59.384 | error | File  "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.8/site-packages/xbox/scripts/rest_server.py",  line 19, in main
xbox.0 | 2021-04-06 14:54:59.384 | error | sys.exit(main())
xbox.0 | 2021-04-06 14:54:59.384 | error | File "/opt/iobroker/node_modules/iobroker.xbox/lib/../python_modules/bin/xbox-rest-server", line 8, in <module>
xbox.0 | 2021-04-06 14:54:59.384 | error | (6174) [START] Failed starting REST server: Process exited with code 1: Traceback (most recent call last):

**Versions:**
 - Adapter version: 0.7.3
 - JS-Controller version: 3.2.16
 - Node version: v12.22.0
 - Operating system: Debian Buster
 - Xbox model: One X

**Comment by foxriver76** [comment]
Yes, the dependency is missing at the smartglass package. I've tried to install it with the adapter, however unfortunately it seems, that we cannot install the requests package in scope of the xbox smartglass package.

Depdening on your python interpreter you have to install it manually via `python3.7 -m pip install requests`

**Comment by AFPass** [comment]
It works. Thanks.
